import Image from "next/image";
import "@app/globals.css";
export const metadata = {
  title: "Jacopas Support Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body id="content">
        <header className="header">
          <Image
            src="/JacoPas_Support.svg"
            alt="JacoPas_Support logo"
            width={20}
            height={20}
            priority
          />
        </header>
        <nav className="navigator">パンくずリストの予定</nav>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
