import "@css/globals.css";

//meta dataの定義
export const metadata = {
  title: "Jacopas Support Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body id="content">
        <header className="header">メール管理</header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
